baseurl = "https://mindsavvy.pages.dev"
defaultContentLanguage = "en"
languageCode = "en"
title = "MindSavvy"
theme = "hugo-theme-dream"

[services]
[services.disqus]
shortname = 'mindsavvy'

[params]
zenMode = true

lightTheme = "emerald"
darkTheme = "forest"

# backgroundImage = "me/background.jpg"
# backgroundImageDark = ""

author = "MindSavvy"
# description = ""
avatar = "img/avatar.png"
headerTitle = "MindSavvy"
# motto = ""

footerBottomText = "MindSavvy is a psychology and mental health website."

# rss = true

# utterancesRepo = ""

# valine = true
# LEANCLOUD_APP_ID = ""
# LEANCLOUD_APP_KEY = ""
# VALINE_LANGUAGE = ""

# email = ""

siteStartYear = 2024

favicon = "favicon.png"

# Syntax highlighting
# customSyntaxHighlighting = true

# options
# stickyNav = true
# reorderNavItems = ["search", "rss", "posts", "categories", "tags"]
# collapseNavItems = ["posts", "categories", "tags"]
# noDefaultSummaryCover = true
# showTableOfContents = true
# showSummaryCoverInPost = true
# showPrevNextPost = true

# [params.navItems]

[params.advanced]
customCSS = ["css/custom.css"]
# customJS = []

# [params.experimental]
# jsDate = true
# jsDateFormat = "yyyy年MM月dd日"
